name: twitter_kit
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  json_serializable: ^3.3.0

flutter:
  plugin:
    androidPackage: info.kitproject.twitter_kit
    pluginClass: TwitterKitPlugin
